### ISSUE TITLE
Top Menu Bar Appearance

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#1]
It seems that when you scroll up the page (in home page for example) the top menu doesn't appear by default. It appears only when scrolling up and if you are at the top of the page, the menu doesn't remains visible. 
here how it was to be working : http://eduardomb.github.io/scroll-up-bar/

Please view the screenshot.
![capture d ecran 2014-12-30 a 15 00 19](https://cloud.githubusercontent.com/assets/10349847/5579299/7733d74c-9038-11e4-8a19-27fc2d565cde.png)

**Comment by nppetrov** [comment]
Woks the same way on my browsers, but I'll ask the guy who did it to check if he can reproduce it.

**Comment by drosne** [comment]
I'm on Mac OSX Lion and use Chrome Version 39.0.2171.95 (64-bit)

**Comment by nppetrov** [comment]
Thanks, will note this as well.

**Comment by nppetrov** [comment]
Just tried it on OSX Chrome as well.. still can't reproduce it. Can you record a short screencast so we can see it?

**Comment by drosne** [comment]
Now it works properly ...
