### ISSUE TITLE
Obsolete elements on MyDetails pages

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#11]
http://beta.refundmyticket.net/personal-area/my-details/
As you can see here we have a text at the bottom which is obsolete. We have to update it with the current text you have in the website please check it out here : http://www.refundmyticket.net/personal-area/my-details/ 
I'm surprised that you didn't see it .. I guessed it's a dynamic text you already have in the wordpress database...

**Comment by krasizlatev** [comment]
I added the text in English .Please send me the text in French.

**Comment by drosne** [comment]
I don't very well understand why you tell me that you don't have the text in french... 
actually you got the english text in the current website, so you can get the french text the same way. You should just client in FR :) May be that text is even dynamic in the admin ? 

may be there is something i don't understand. 
http://www.refundmyticket.net/fr/personal-area/my-details/

**Comment by krasizlatev** [comment]
Fixed. There was simply problem with this text not being displayed in french on the beta so I thought there was no translation.

**Comment by drosne** [comment]
Alright !
