### ISSUE TITLE
My Details Page : Drop down menus "My Country" / "My Language"

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#13]
I think that there is missing something in that page "My Details" 
when we display the already filled elements the two drop downs dedicated to My Country and My Language are both not defined. That means that we have two dropdown with a country and and language but we don't very well understand what they corresponds to. 
So can you please add above it : "My Country" / "Mon Pays"    "My Choosen Language" / "Mon choix de langue"
You can find the PSD if you need it here : 
https://www.dropbox.com/s/2ireb3p1h5yszfg/dropDownMenu%20in%20MyDetails.psd?dl=0

![dropdownmenu-in-mydetails](https://cloud.githubusercontent.com/assets/10349847/5627691/49101a24-959c-11e4-83d6-34e09fd68666.jpg)

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
Thanks
