### ISSUE TITLE
Little bug in the "News List" Page

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#14]
Please make the whole text to be clickable in order to reach the Article Page. 

Then when i make a search, the search i have typed doesn't remain visible in the "search field". PLease leave it there in order to make it more easy to follow/understand. 

Please notice that it also should be the same if you click on a "tag" keyword.

Please let me know also if you can add an "autocompletion" feature there easily to make it more useful. 
this autocompletion would many consider the keywords or title of the articles. 

please don't also forget to integrate the Latest News list on the right side. it seems that currently it's empty.

I'm surprised to see there that there is no footer like in other page Please integrate it... 
![capture d ecran 2015-01-06 a 12 14 30](https://cloud.githubusercontent.com/assets/10349847/5627776/9f449fae-959d-11e4-9ae1-27d8277c5791.png)

**Comment by krasizlatev** [comment]
- I made the search word appear after you done a search
- When you click on a tag where do you want to be shown ?
- I added autocompletion, please check it
- The footer is also added

**Comment by drosne** [comment]
1- OK 
2- same place (inside the search field)
3- do you use elastic search from heroku or a ready made plugin from WordPress community ? 
4- OK

**Comment by drosne** [comment]
I tested the autocompletion ... it seems not working properly ... still loading after several min
![capture d ecran 2015-01-09 a 15 46 42](https://cloud.githubusercontent.com/assets/10349847/5681219/d1d392d8-9816-11e4-9c8f-e66246eb9565.png)

**Comment by drosne** [comment]
Please make the whole text to be clickable in order to reach the Article Page.

Then when i make a search, the search i have typed doesn't remain visible in the "search field". Please leave it there in order to make it more easy to follow/understand.

Please notice that it also should be the same if you click on a "tag" keyword.

Please let me know also if you can add an "autocompletion" feature there easily to make it more useful. This autocompletion would many consider the keywords or title of the articles.

**Comment by krasizlatev** [comment]
I checked the autocompletion and for me it worked fine. Please re-check it.
I would not advise that when a user clicks on a tag the tag gets inside the search field. For some reason Wordpress doesn't consider the tags when searching so if you type "elephant" which is a tag of the post there will not be any results.

**Comment by drosne** [comment]
OK
