### ISSUE TITLE
Footer Menu

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#15]
I just have seen that the Footer Menu is not dynamic. 
Can you please make it dynamic in order to avoid problem of update. 
For example right now, Trouble With Luggages, is still "Trouble With My Luggages"

**Comment by krasizlatev** [comment]
I added the footer menu in Admin -> Menus.

**Comment by drosne** [comment]
I don't know what to think... actually it's ok to update the footer menu..but i was more expecting something like dynamic. if you change the name of the page, the menu change automatically (something like that...)... well it's not very very important... let's consider that it's ok for now. In order to concentrate on the most important ...
