### ISSUE TITLE
Airport Field Autocompletion.

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#17]
i feel like the autocompletion of the airport field in the claim form is very slow... 
I was wondering if you used the Elastic Search Module from Heroku to do it ? 
Actually the system is supposed to be based on Heroku smartness and efficiency so let's not forget to use it :)
![capture d ecran 2015-01-09 a 10 56 15 2](https://cloud.githubusercontent.com/assets/10349847/5678033/39d4324e-97ee-11e4-9d40-99cfbf3113ed.png)

**Comment by krasizlatev** [comment]
I'm really not sure why it's slow for you. On the beta version there are currently only some 30 airports so normally it should be very fast. We are not using Elastic, it's for searching within the whole website while here we search only within a small table of 30 records.

**Comment by drosne** [comment]
ok but then you'll connect to all airports and may be it's gonna be longer.. i don't know when it's not connected to correct database and when it will be .. but that's quite ok if it's fast... but right now, it's faster on heroku (prod) hosting than on OVH (beta)

**Comment by drosne** [comment]
ok let's say that it's ok... i'll wait for testing with the whole airport database... we will see what happens... 
however, as you can see here, i'm able no to select a airport ... we were supposed to commit this and it seems it was working .. that's strange .. 

![capture d ecran 2015-01-28 a 15 27 57](https://cloud.githubusercontent.com/assets/10349847/5939225/46f52500-a702-11e4-9587-59de01460ad9.png)

**Comment by krasizlatev** [comment]
It's possible if you don't wait for the whole page to finish loading and you start typing, but it's highly unlikely...
I don't manage to achieve what this problem. I can put whatever i went in the text field, but I cannot continue with the Next button.

**Comment by drosne** [comment]
sorry ... i'm not sure to well understand what you mean here ...

**Comment by krasizlatev** [comment]
You said you can type "whatever you want" in the from/to field. 
Normally the next button will not allow you to proceed.
It's possible that it will allow you if the whole page has not finished loading and you started to type very quickly and pressed the next button. but it's very unlikely, it's possible on slow connections.

**Comment by drosne** [comment]
OK i understand how it works now... i guess it's quite ok ...
