### ISSUE TITLE
Problem with the share icons in news page

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#21]
In the News pages we have something not well responsive with the share icons. Can you please fix this. 
![photo 5](https://cloud.githubusercontent.com/assets/10349847/5738872/d0ee0176-9bf1-11e4-8359-af4d412e6dea.PNG)
![photo 3](https://cloud.githubusercontent.com/assets/10349847/5738886/0f394486-9bf2-11e4-93e0-c98d8474785e.PNG)

**Comment by nppetrov** [comment]
HTML/CSS is different than the one we provided, but I guess adding max-size to the pngs you have used on each breakpoint will do. However, it's better to use svg for these icons in order to keep hq.

**Comment by krasizlatev** [comment]
Fixed.

**Comment by drosne** [comment]
yes it is... perfect Thanks
