### ISSUE TITLE
Missing items in the footer.

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#22]
It seems that an icon "News" / "Actualités" has been forgotten in our different Mobile Menu. 
Can you please fix this. 
![photo 4](https://cloud.githubusercontent.com/assets/10349847/5738905/498dbce8-9bf2-11e4-8279-b5f34ce7f17c.PNG)

**Comment by nppetrov** [comment]
Do you mean only adding the "NEWS" link or there's also an icon for it (like on "LOGIN")? There's no "NEWS" menu item in the designs we have.

**Comment by drosne** [comment]
nope, no icon to be added, exactly like "contact" between our "rights" and "about"

**Comment by nppetrov** [comment]
I believe that menu will be (if not already) a dynamic WP menu, so managing links should be done in the WP admin.

**Comment by drosne** [comment]
according to what i have understood... at this step, krasi decided not to make it dynamic... 
don't ask me why :)

----------------------------------------------------------------
Romain DROSNE 
Co-Founder

Claim Assistance 
Get up to 800$ for a delayed flight ! 

www.RefundMyTicket.net
www.RembourserMonBillet.com

@RefundMyTicket
----------------------------------------------------------------

**Comment by nppetrov** [comment]
I see.. I assigned this to him anyway, so he can add it to the template in that case.

**Comment by krasizlatev** [comment]
Fixed.

**Comment by drosne** [comment]
good ! closed
