### ISSUE TITLE
Inside the airport fields

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#29]
Strangely in the First Airport field we have "london heathrow airport".. actually this is a misunderstanding 
inside the Airport Field, it is supposed to be, by default, the same thing everywhere. 
Please put the following : 
EN : "City of your airport"
FR : "Ville de votre aéroport"

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
Yes good, however the user SHOULD select one of the proposal. Currently we can simply right london... 
we should not be able to work what we want... we have to commit the user to select something in the dropdown which appear when you started to type.

**Comment by krasizlatev** [comment]
Done. Please re-check.

**Comment by drosne** [comment]
yes works thanx
