### ISSUE TITLE
Latest Eligible Slider

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#3]
If you check the Latest Eligible Slider in the mobile version you'll see that you can slide the different elements (not using the arrow but simply sliding right and left) as the other sliders works like this. 
So i guess this specific slider has a little bug. 
![photo](https://cloud.githubusercontent.com/assets/10349847/5579620/056f8dee-903e-11e4-941b-8e68da4a15f7.PNG)

**Comment by nppetrov** [comment]
It's probably a bug from jCarousel (the slider plugin) as it slides from time to time, but not on each attempt. I'll check with the developer who did the sliders tomorrow (he is not working today).

**Comment by drosne** [comment]
I guess i just understood why it's like that ... 
actually as the elements are clickable, you can't add a slide left and right on it... (or may be you can but something has been in conflict... i have already met such kind of problems... we didn't succeed to solve it... but it was some kind of 4 years ago ... so may be now there are some tricks for this

**Comment by nppetrov** [comment]
I didn't notice the elements are clickable when I checked it on my phone. It does make sense though, since the events are connected  (click and drag). So probably that's the reason.

**Comment by drosne** [comment]
All right ! so i close the issue
