### ISSUE TITLE
In step 4 text is missing.

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#32]
As you can see in that design it's supposed to have a text on the top of the form to explain. 
here is the following missing text : 
EN : "Please tell us your initial flight plan"
FR : "Merci de nous donner votre plan de vol initial"

**Comment by krasizlatev** [comment]
I'm not sure on which page is that. When I go to the "Impacted flights" section of the form there is on top the test "Please tell us what are the flights you were supposed to take initially" should I change it to "Please tell us your initial flight plan" or you are talking about another page ?

**Comment by drosne** [comment]
sorry forgot to attach the screenshots
![capture d ecran 2015-01-26 a 17 58 44](https://cloud.githubusercontent.com/assets/10349847/5903943/01b495ee-a585-11e4-906b-4a8cef5aa799.png)

"Please tell us your initial flight plan"
"Merci de nous faire part de votre plan de vol initial"
 
with this design 

![rmtck02_claim_03_en](https://cloud.githubusercontent.com/assets/10349847/5904001/7b0a3a5c-a585-11e4-8da3-2a90ca207a1b.jpg)

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
good thanks
