### ISSUE TITLE
In summary of my Initial Flight Plan, problem of airport name

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#35]
As you can see here, the airport names are far too long and break the high of the page which is supposed to be "stuck" to match a ipad screen without scrolling....
can you please display the airport name with only the following description : 

Paris (CDG) - Beijing (PEK) ?

![capture d ecran 2015-01-26 a 18 03 43](https://cloud.githubusercontent.com/assets/10349847/5904063/0c027092-a586-11e4-8fa3-1d01a4b5fd4e.png)

like you did here even if i guess it would be even better not to display the country fullname : 
![capture d ecran 2015-01-26 a 18 07 33](https://cloud.githubusercontent.com/assets/10349847/5904080/41180ed6-a586-11e4-95a2-d44bfbbc88a7.png)

**Comment by krasizlatev** [comment]
Done.
