### ISSUE TITLE
Display Harmony in Claim Form page

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#36]
Here you can also see that the fact of not having the airport name only written with the name of the city + the IATA code is breaking the design. Please display the city and then the IATA code only. 

Please check also to have the top "explanation title text" center in the middle with the same font like on every other claim page. 
![capture d ecran 2015-01-26 a 18 09 51](https://cloud.githubusercontent.com/assets/10349847/5904141/c8f3f0cc-a586-11e4-9160-705dbadee42f.png)

But in that case please also keep in mind that modification required as some pages are missing 
please see the bug #33  
https://github.com/drosne/RMT/issues/33

You'll see that we have to modify a little bit the process of rebooking flight to get the actual flight plan due to the fact that sometime to solve a single leg problem, the company rebook a multiple leg flight (or the opposite)... which means that we have to make it a bit more complex...

**Comment by krasizlatev** [comment]
This is fixed, I'll check 33 separately.

**Comment by drosne** [comment]
yes good !
