### ISSUE TITLE
Final Text break the design 

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#38]
As you can see in that design, the high we want to stick to keep the whole important content visible on a tablet is broken due to the size of the text. 
Actually, can you please make the text larger in terms of width. So we won't have so many text lines and so the text and button will be kept in the efficient zone (which means visible on a tablet browser size (without scolling)

![capture d ecran 2015-01-27 a 10 40 22](https://cloud.githubusercontent.com/assets/10349847/5916395/f82b00bc-a610-11e4-9c19-c53503164014.png)

**Comment by krasizlatev** [comment]
Please recheck. Should be fine now.

**Comment by drosne** [comment]
Not so much actually ... 
Please delete the last sentence "Hit the button below to launch the procedure" (in france too)
to save also some vertical space. (May be you can save also some space above "according to those first details"...
![capture d ecran 2015-01-28 a 12 26 57](https://cloud.githubusercontent.com/assets/10349847/5936855/faba1970-a6e8-11e4-87c2-212d64f7aad7.png)

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
yes very much better !
