### ISSUE TITLE
Little display optimisation in Claim Form page.

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#39]
Can you please in that page do 2 things : 
* Put the worked "Rebooked" in red in order to make it more visible. 
* Align the flight details of the delayed flight on the left as described in the following screenshot
![capture d ecran 2015-01-28 a 12 32 31](https://cloud.githubusercontent.com/assets/10349847/5936917/c7468e1a-a6e9-11e4-82fa-ab1843c98201.png)

**Comment by krasizlatev** [comment]
Done.
