### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#4]
I don't know if everything is well dynamic in the top menu for mobile version but what i can see is that there are some mistakes in the spelling of the menu like (Trouble Width a Flight" instead of "Trouble With a Flight"... i guess this is because the menu is still not dynamic. Please let me know about that...
![photo](https://cloud.githubusercontent.com/assets/10349847/5579702/37ff6094-903f-11e4-98a3-c5262ce14641.PNG)

**Comment by nppetrov** [comment]
Yes, that's plain html only, so once you integrate it into WordPress, you  will be able to easily control all of those.

**Comment by drosne** [comment]
Ok So it will be managed by Krasi as soon as it will have been dynamic...

**Comment by krasizlatev** [comment]
Romain, I fixed the errors in the texts. The texts are not dynamic, sorry, I know it's not the best way, but it was the quickest way. If you prefer I'll add the menus inside Wordpress so you can manage them,

**Comment by drosne** [comment]
Let's wait for this...
Thanks 

Romain DROSNE 
Mob : +33 6 62 45 13 64
