### ISSUE TITLE
Claim Form page incoherence Delayed / Delayed

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#40]
Please have a look there : 
![capture d ecran 2015-01-28 a 12 25 52](https://cloud.githubusercontent.com/assets/10349847/5936948/124c3af4-a6ea-11e4-807e-84d9b918d439.png)

you'll see that if i select delayed for the second flight instead of the first, both of them are delayed. 
Actually, if i select the first leg as "delayed" the followings become "missed" and if i selected the second leg as "delayed" the previous legs become "OK" (in green)

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
perfect
