### ISSUE TITLE
Admin and translation in home page

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#41]
can you please check if i can update the following titles and text "They already have been refunded" and "Latest eligible flights, Click on your flight to start a claim...

Then the "Delayed" (Retardé), "Cancelled" (Annulé) are not translated...

**Comment by krasizlatev** [comment]
I fixed Delayed" (Retardé), "Cancelled" (Annulé) , but the texts  "They already have been refunded" and "Latest eligible flights, Click on your flight to start a claim... are not editable from the admin for the moment.

**Comment by drosne** [comment]
Ok so please for the moment update them with the following : 
- Derniers vols éligibles à une compensation / Latest flights entitled to a compensation

Actually then the link on the flights is supposed to lead to the form with the pre-filled fields... 
but at this step, i think it's secondary features ... so please get the click on the different flight out... 
so now we are not able to click to be driven to the pre filled claim.. 

And switch the text with "Discover here the latest delayed and cancelled flights in Europe"
"Découvrez ici les derniers vols retardés et annulés en Europe"

**Comment by krasizlatev** [comment]
Sorry Romain, I'm not sure which text should be changed with what.
They already got refunded ? should I change it with something
Latest eligible flights - I should change it with "Derniers vols éligibles à une compensation / Latest flights entitled to a compensation" ?
Where to put "Discover here the latest delayed and cancelled flights in Europe"
"Découvrez ici les derniers vols retardés et annulés en Europe" ?

**Comment by drosne** [comment]
nothing to change about they already got refunded... 
only allow more testimonies...

Then for the latest flight eligible (see the screenshot below)... i hope it helps
"Discover here the latest delayed and cancelled flights in Europe"
"Découvrez ici les derniers vols retardés et annulés en Europe" ?

first sentence : "![capture d ecran 2015-02-02 a 15 52 35](https://cloud.githubusercontent.com/assets/10349847/6002434/8b3be01a-aaf3-11e4-96be-f754b561350e.png)

**Comment by krasizlatev** [comment]
I changed the text, maybe it's a bit long now...
Also changed the photos of the carrousel.

**Comment by drosne** [comment]
you are right ... so let's simply write "Latest delayed and cancelled flights"

**Comment by krasizlatev** [comment]
Ok, I put
Latest delayed and cancelled flights
Les derniers vols retardés et annulés

**Comment by drosne** [comment]
perfect !
