### ISSUE TITLE
Menu Items

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#42]
Well i have tried to update the "News" / "Actualités" in the website menu using the Menu module in wordpress : http://beta.refundmyticket.net/wp-admin/nav-menus.php
actually it didn't work as it seems that this specific item is not dynamic / included in that menu list. 
can you please add it too...

Actually i want to call it "Blog"
and switch 
Actualités récentes > Articles Récents
Rechercher une actualité > Rechercher un article

Latest News > Latest Articles
Search for a news > Search for a article

**Comment by krasizlatev** [comment]
Done.
