### ISSUE TITLE
Top menu update broken

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#43]
It seems that the top items in the menu are not updated with the admin system... 
I have changed the title of the page "Our Rights" / "Nos Droits" into "Your Rights" / "Vos Droits" 
and it doesn't update anywhere... 
i would like to be able to update this .. i think it could be useful to make menu items dynamic and modifyable... 
please adjust this.

**Comment by krasizlatev** [comment]
I fixed this for the top menu.

**Comment by drosne** [comment]
ok good ... now please make it also updated in the page : 
http://beta.refundmyticket.net/fr/category/news/
News > Blog
Rechercher une actualité > Rechercher un article
Search a news > Search for an article

Actualités récentes > Articles récents
Latest News > Latest Articles

**Comment by drosne** [comment]
and please add Blog part inside the footer menu too...

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
It remains "NEWS" in the title of the page and instead of "BLOG" please fix it too.

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
great thanks
