### ISSUE TITLE
French Wording for the final button "Lancer

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#51]
"Please tell us which flight has been delayed ?"
please write:
"Please select the flight which has been delayed"

and in french 
"Merci de nous préciser quel vol a été retardé ?"
"Merci de sélectionner le vol retardé"

![capture d ecran 2015-02-12 a 22 08 32](https://cloud.githubusercontent.com/assets/10349847/6177424/f504b34e-b306-11e4-96dd-cd44add31525.png)

In English: 

"According to those first details,
your claim might be eligible for a refund up to 600€
However, the commitments of the airline company depend on the reasons of this flight delay.
So, we can launch a claim procedure but it's quite possible that after being aware of the exact reasons of this delay, your claim become not eligible to any compensation."

Should become 
"According to those first details,
your claim might be eligible for a refund up to 600€
We propose to claim this for you in front of the airline company"

Button "Refund My Ticket" switch to "Get my compensation !"

In french:
![capture d ecran 2015-02-12 a 22 41 02](https://cloud.githubusercontent.com/assets/10349847/6177599/47f91b7a-b308-11e4-9d14-ef7bee899366.png)

"Au regard de ces premières informations
Votre plainte devrait être éligible à un remboursement de 600€
Cependant, les obligations d'indemnisation pour la compagnie aérienne dépendent des raisons exactes qui justifient le retard de votre vol.
Nous pouvons donc lancer une procédure mais il est possible qu'après vérification de cette raison, votre réclamation ne trouve pas d'issues favorables."

"Au regard de ces premières informations
Votre plainte a priori éligible à un remboursement de 600€
Nous vous proposons d'effectuer pour vous cette réclamation auprès de la compagnie aérienne."

Button : "Rembourser mon billet !" switch to "Obtenir mon indemnisation !"

**Comment by krasizlatev** [comment]
Done.

**Comment by drosne** [comment]
Thx
