### ISSUE TITLE
General Display of the page "Problem with a Train"

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#7]
As you can see in the page "Problem with a train" we have a some trouble with the way the page appears in the mobile version. I guess there is a little problem with the CSS... 
Can you please check and fix this ? 
![photo](https://cloud.githubusercontent.com/assets/10349847/5627404/ca02c136-9597-11e4-8a16-cec42ee302d0.PNG)

**Comment by nppetrov** [comment]
Just checked our local (html only) copy and it looks fine. I guess the problem with the integration comes from the quotes on the <a> tags. They seem to be broken (extra quotes are added) and that seems to be the reason for the broken layout. Perhaps Krasi can check that and fix the tags.

**Comment by drosne** [comment]
Krasi ?

**Comment by krasizlatev** [comment]
Should be fine now.

**Comment by drosne** [comment]
i tested it on my phone and even cleared my cache but i get the same result ...

**Comment by krasizlatev** [comment]
It's fixed using the fix from Nikola.

**Comment by drosne** [comment]
yes works
