### ISSUE TITLE
Visual Problem with My Trips page

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#8]
As you can see currently in the beta : http://beta.refundmyticket.net/personal-area/my-trips/
we have several problem that i would like to fix. 
1- the little "cursor" to signify the part you are in is still on "MyClaims" instead of "My Trips" I guess there is something to fix here. 
2- The fact that the row is "clickable" (as when you arrive it's close and not open) is not visible. There is no roll over effect. So i think it deserve it. Some kind of a very light grey background appearing when rolling over. 
3- I think that "Theses details are wrong? Contact Us" is not supposed to be positioned here but on the right hand on the same row than the passenger name wasn't it ? 
4- On the little "clock icon" we were supposed to have a dialog bubble appearing in roll over to provide more details about the schedule and actual time of that flight. Please add it

**Comment by nppetrov** [comment]
This page is visible upon login, so I was unable to check #1. Not able to find reg form either, can you provide me with some login, so I can check again? As far as the others:

2. Background added, will send you updated files later today, so you can confirm if that's what you had in mind.
3. We did it the same as mobile version, as desktop design was not provided.
4. Same as #3 - there was no design provided for that.

**Comment by drosne** [comment]
try login in with krasi.zlatev@gmail.com / test

**Comment by nppetrov** [comment]
Okay, saw it. The confusion is coming from the markup, since we have two classes called "current". One on the <code><li></code> element, and one on the <code></a></code> element. Only the second one is needed. That's our fault, as our developer forgot to remove the <code><li></code> class. Sorry about that.

So in order to get this working properly, Krasi should add "current" class to the <code><a></code> element.

**Comment by drosne** [comment]
Krasi ?

**Comment by drosne** [comment]
As you can see currently in the beta : http://beta.refundmyticket.net/personal-area/my-trips/
we have several problem that i would like to fix. 
1- the little "cursor" to signify the part you are in is still on "MyClaims" instead of "My Trips" I guess there is something to fix here.

OK that's done ! 

2- The fact that the row is "clickable" (as when you arrive it's close and not open) is not visible. There is no roll over effect. So i think it deserve it. Some kind of a very light grey background appearing when rolling over. 

Ok that's done !

3- I think that "Theses details are wrong? Contact Us" is not supposed to be positioned here but on the right hand on the same row than the passenger name wasn't it ?

That's quite strange... please find it here : https://www.dropbox.com/s/0r7sfju1b90g5lm/RMTCK06_MyClaims_EN-MyTrips.jpg?dl=0

4- On the little "clock icon" we were supposed to have a dialog bubble appearing in roll over to provide more details about the schedule and actual time of that flight. Please add it

Same JPEG : https://www.dropbox.com/s/0r7sfju1b90g5lm/RMTCK06_MyClaims_EN-MyTrips.jpg?dl=0
![rmtck06_myclaims_en-mytrips](https://cloud.githubusercontent.com/assets/10349847/5678213/41598030-97f0-11e4-8428-5d160163ec4b.jpg)

**Comment by nppetrov** [comment]
I'm getting 404 for both, perhaps they were not shared with me?

**Comment by drosne** [comment]
i fixed something .. please reload the github page and try again

**Comment by nppetrov** [comment]
Do you need just 3 and 4 to be applied or the whole page to be restyled (as there are other small differences as well)? Each case I'll have to add a charge for few to couple of more hours, since we didn't have this in the beginning...

**Comment by drosne** [comment]
arf... i would prefer to have it done as planned in the design... i don't know why you didn't have that page before... 
i'm quite disturb... anyway, if you want to charge some hours ... i understand just let me know first and i'll agree or not

**Comment by drosne** [comment]
I added the sources in .AI in french and english in the source folder in the dropbox... 
Sorry for that forgotten file

**Comment by nppetrov** [comment]
Latest files sent by e-mail.

**Comment by drosne** [comment]
job is done yes ... 
Krasi please don't forget the PHP dev dealing with the bubble too...
