### ISSUE TITLE
Php Bug on "MyTrips page"

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#9]
I think something has been missed in the MyTrips page . Actually there is a claim made on the sample you have provide to me (with Krasi.Zlatev@gmail.com / test) and if you check the "Claim" column, you got "NONE" inside instead of "Pending" or "Closed" as there is a claim for this trip.
Please check and fix this.

**Comment by drosne** [comment]
please don't also forget to check the adjustment from Nikola in MyTrips and especially don't forget the dialog bubble opening on clock icon.

**Comment by krasizlatev** [comment]
I fixed the Pending/Closed issue.

**Comment by drosne** [comment]
ok good
